language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t wn.ai/wn-react-template-docker -f Dockerfile.dev .
    
script:
    - docker run -e CI=true wn.ai/wn-react-template-docker npm run test
