language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t wojciechnowak.ai/wn-react-template-docker -f Dockerfile.dev .
    
script:
    - docker run -e CI=true wojciechnowak.ai/wn-react-template-docker npm run test
    